import { Inter } from "next/font/google";
import "./globals.css";
import UserContextProvider from "./context/UserContext";
import PostContextProvider from "./context/PostContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DummyAPI Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <PostContextProvider>
      <UserContextProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </UserContextProvider>
    </PostContextProvider>
  );
}
